# Generated by Django 4.2 on 2023-04-30 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='starts',
            new_name='stars',
        ),
    ]
